apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flux2
  labels:
    app: nginx-flux2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-flux2
  template:
    metadata:
      labels:
        app: nginx-flux2
    spec:
      containers:
      - name: nginx-flux
        image: nginx:1.14.2
        ports:
        - containerPort: 80
